# reference: https://verdantfox.com/blog/view/how-to-use-git-pre-commit-hooks-the-hard-way-and-the-easy-way
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
        args:
          - --unsafe
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.52.2
    hooks:
      - id: golangci-lint
  - repo: local
    hooks:
      - id: gofmt-fixer
        name: gofmt
        entry: gofmt -w .
        language: golang
        types: [go]
      - id: check-license-signature
        name: license-signature-automation
        entry: ./hack/maintenance/append_license_signature.sh
        language: script
        files: \.go$
